version: '3.3'
services:

    backend:
        image: rayirl/carbonmix-backend:testing
        container_name: backend
        platform: linux/amd64
        ports:
            - '3000:3000'
        restart: unless-stopped
        labels:
        - "traefik.http.routers.backend.rule=Host(`carbonmix.raywilson.ie`) && PathPrefix(`/api`)"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
