name: CI
on:
  push:
    branches:
      - main
      - deploying-to-production
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Setup pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm nx build backend




#name: CI
#on:
#  push:
#    branches:
#      - main
#      - deploying-to-production
#  pull_request:
#
#jobs:
#  main:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      # Setup pnpm
#      - uses: pnpm/action-setup@v2
#        with:
#          version: 8
#      - run: pnpm install --no-frozen-lockfile
#      - run: pnpm nx run-many -t build -p backend
#      - run: pnpm nx run-many -t test -p backend


#  test:
#    permissions:
#      contents: 'read'
#      id-token: 'write'
#    timeout-minutes: 20
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Install PNPM
#        run: npm install -g pnpm --dev
#
#      - name: Install dependencies
#        run: pnpm install --dev
#
#      - name: Build frontend
#        run: pnpm nx run frontend:build
#
#      - name: Build backend
#        run: pnpm nx run backend:build
#
#      - name: Test backend
#        run: pnpm nx run backend:test
