name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    permissions:
      contents: 'read'
      id-token: 'write'
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build frontend
        run: pnpm nx run frontend:build

      - name: Build backend
        run: pnpm nx run backend:build

      - name: Build backend
        run: pnpm nx run backend:test
